version: "3.9"

services:
    backend:
        build: .
        command: bash -c "python ./app/create_tables.py && python ./app/__main__.py"
        environment:
            DATABASE_URL: "postgresql://postgres:password@database:5432/PredictiveMaintenance"
            DEVELOPMENT_MODE: True
            SERVER_PORT: 8000
            WINDOW_SIZE: 10
            SEQUENCE_SIZE: 50
        depends_on:
            - database
        ports:
            - 8000:8000
    database:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: PredictiveMaintenance
        ports:
            - 5432:5432
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data: {}
